DROP TABLE WORDS IF EXISTS;

CREATE TABLE WORDS (
   theWord varchar(50),
   length INT,
   countA INT,
   countB INT,
   countC INT,
   countD INT,
   countE INT,
   countF INT,
   countG INT,
   countH INT,
   countI INT,
   countJ INT,
   countK INT,
   countL INT,
   countM INT,
   countN INT,
   countO INT,
   countP INT,
   countQ INT,
   countR INT,
   countS INT,
   countT INT,
   countU INT,
   countV INT,
   countW INT,
   countX INT,
   countY INT,
   countZ INT
);
